
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.hexerei]
				crow = true

			[light_sources.settings.entities.soulsweapons]
				evil_forlorn = true
				dark_sorcerer = true
				withered_demon = true

			[light_sources.settings.entities.mowziesmobs]
				umvuthana_raptor = true
				umvuthi = true
				sunstrike = true
				boulder_projectile = true
				foliaath = true
				poison_ball = true
				umvuthana_follower_raptor = true
				umvuthana = true
				grottol = true
				naga = true
				ferrous_wroughtnaut = true

			[light_sources.settings.entities.blue_skies]
				crystal_camel = true
				shade_monitor = true

			[light_sources.settings.entities.alexsmobs]
				kangaroo = true
				blue_jay = true
				bone_serpent_part = true
				cachalot_echo = true
				catfish = true
				laviathan = true
				tasmanian_devil = true
				rhinoceros = true
				comb_jelly = true
				skunk = true
				roadrunner = true
				rattlesnake = true
				leafcutter_ant = true
				blobfish = true
				lobster = true
				snow_leopard = true
				grizzly_bear = true
				flutter = true
				orca = true
				maned_wolf = true
				crow = true
				elephant = true
				crocodile = true
				crimson_mosquito = true
				hammerhead_shark = true
				seal = true
				emu = true
				triops = true
				mimic_octopus = true
				gazelle = true
				soul_vulture = true
				guster = true
				tusklin = true
				void_portal = true
				terrapin = true
				flying_fish = true
				bone_serpent = true
				froststalker = true
				bald_eagle = true
				seagull = true
				raccoon = true
				fly = true
				giant_squid = true
				alligator_snapping_turtle = true
				toucan = true
				cachalot_whale = true
				hummingbird = true
				frilled_shark = true
				bison = true

			[light_sources.settings.entities.cgm]
				throwable_grenade = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_enderman = true
				mutant_creeper = true
				creeper_minion_egg = true
				mutant_skeleton = true
				mutant_zombie = true
				mutant_arrow = true

			[light_sources.settings.entities.mca]
				male_zombie_villager = true
				female_zombie_villager = true
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.sn0wfrogs_capybaras]
				capybara = true

			[light_sources.settings.entities.jeg]
				flare_projectile = true
				sonic_projectile = true
				rocket = true
				spectre_projectile = true
				blaze_projectile = true

			[light_sources.settings.entities.biomeswevegone]
				pumpkin_warden = true
				oddion = true

			[light_sources.settings.entities.illagerinvasion]
				provoker = true
				basher = true
				firecaller = true
				marauder = true

			[light_sources.settings.entities.galosphere]
				sparkle = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				nameless_hanged = true
				revenant = true
				corrupted_vindicator = true
				skeleton_creeper = true
				corrupted_pillager = true
				ghoul = true
				reaper = true
				nightmare = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				bluejay = true
				snake = true
				catfish = true
				dragonfly = true
				robin = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				rattlesnake = true
				zebra = true
				canary = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				lizard_tail = true
				finch = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				cerberus = true
				tank = true

			[light_sources.settings.entities.tacz]
				bullet = true

			[light_sources.settings.entities.conjurer_illager]
				bouncing_ball = true
				throwing_card = true

			[light_sources.settings.entities.betternether]
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				skull = true
				naga = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.bakery]
				wandering_baker = true

			[light_sources.settings.entities.giants_overhaul]
				giant_drowned = true

			[light_sources.settings.entities.takesapillage]
				skirmisher = true
				archer = true
				clay_golem = true

			[light_sources.settings.entities.iceandfire]
				stymphalian_bird = true
				pixie = true
				siren = true
				lightning_dragon = true
				hippocampus = true
				fire_dragon_charge = true
				hippogryph = true
				troll = true
				hydra_multipart = true
				ice_dragon_charge = true
				fire_dragon = true
				cylcops_multipart = true
				hydra = true
				ice_dragon = true
				multipart = true
				dragon_multipart = true
				cyclops = true
				amphithere = true
				sea_serpent = true

			[light_sources.settings.entities.bygonenether]
				piglin_hunter = true
				wraither = true
				piglin_prisoner = true
				wex = true
				warped_enderman = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				gauntlet = true

			[light_sources.settings.entities.ars_nouveau]
				starbuncle = true
				gift_starby = true
				drygmy = true
				whirlisprig = true

			[light_sources.settings.entities.minecells]
				custom_arrow = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.untitledduckmod]
				duck = true
				goose = true

			[light_sources.settings.entities.twilightforest]
				helmet_crab = true
				minotaur = true

			[light_sources.settings.entities.iter_rpg]
				spiderling = true
				scallop = true
				goblin = true
				debug_mobmorph = true
				goblin_warrior = true
				hobgoblin = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				moobloom = true
				mauler = true
				crab = true
				rascal = true

			[light_sources.settings.entities.crimsonsteves_mutant_mobs]
				withered_boxer = true
				mutant_skeleton = true
				stunt_skeleton_upper_body = true
				withered_hopkeleton = true
				hopkeleton = true

			[light_sources.settings.entities.fd]
				chairexecution = true
				foxy = true

			[light_sources.settings.entities.terramity]
				unholy_lance_projectile = true
				throwing_bomb_projectile = true
				fireball_projectile_projectile = true
				holy_round_projectile_projectile = true
				blue_fairy = true
				laser_projectile = true
				water_blast_projectile = true
				megabite = true
				anti_gravity_round_projectile_projectile = true
				pink_fairy = true
				virtue = true
				guided_energy_blast_projectile = true
				gold_round_projectile_projectile = true
				dungeon_effigy = true
				simple_turret = true
				gatmancer = true
				meteor = true
				enderswap_projectile_projectile = true
				bomb_flower_item_projectile = true
				daemonium_shotshell_projectile_projectile = true
				dungeon_sentry = true
				hellrok = true
				elite_skeleton = true
				green_fairy = true
				echo_bug = true
				tg_hand = true
				lightning_bolt = true
				cave_gnome = true

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				zoglin = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				mule = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				rabbit = true
				silverfish = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				phantom = true
				minecart = true
				evoker = true
				llama_spit = true
				warden = true
				glow_squid = true
				glow_item_frame = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				evoker_fangs = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				illusioner = true
				potion = true
				trident = true
				wolf = true
				villager = true
				skeleton_horse = true
				tnt_minecart = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.alexscaves]
				vallumraptor = true
				hullbreaker = true
				grottoceratops = true
				tremorsaurus = true
				subterranodon = true
				trilocaris = true
				gossamer_worm = true
				relicheirus = true

			[light_sources.settings.entities.handcrafted]
				seat = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				desert_enderman = true
				coral_enderman = true
				snowy_enderman = true
				swamp_enderman = true
				warped_forest_enderman = true

			[light_sources.settings.entities.babyfat]
				ranchu = true

			[light_sources.settings.entities.collectorsreap]
				chieftain_crab = true
				tiger_prawn = true
				platinum_bass = true
				clam = true
				urchin = true

			[light_sources.settings.entities.sonicraft]
				crabmeat = true
				blast_processing_primed = true
				flicky = true

			[light_sources.settings.entities.knightquest]
				gremlin = true
				eldknight = true
				ghosty = true
				eldbomb = true

			[light_sources.settings.entities.unusualprehistory]
				sludge = true
				iceberg_smilodon = true
				iceberg_mammoth = true

			[light_sources.settings.entities.born_in_chaos_v1]
				firelight = true
				zombie_fisherman = true
				decaying_zombie = true
				fallen_chaos_knight = true
				dark_vortex = true
				glutton_fish = true
				corpse_fish = true
				skeleton_thrasher = true
				siamese_skeletons = true
				zombie_bruiser = true
				pumpkin_pistol_projectile = true
				bonescaller_not_despawn = true
				siamese_skeletonsleft = true
				bloody_gadfly = true
				zombie_clown = true
				door_knight = true
				siamese_skeletonsright = true
				thornshell_crab = true
				maggot = true
				door_knight_not_despawn = true
				spiritof_chaos = true
				skeleton_demoman = true
				decrepit_skeleton = true
				baby_spider = true
				spirit_guide_assistant = true
				dread_hound = true
				supreme_bonescaller_not_despawn = true
				decaying_zombie_not_despawn = true
				baby_skeleton = true
				swarmer = true
				zombie_lumberjack = true
				barrel_zombie = true
				restless_spirit = true
				bonescaller = true
				phantom_creeper = true
				dire_hound_leader = true
				supreme_bonescaller = true
				baby_skeleton_minion = true
				mother_spider = true
				bone_imp_minion = true
				phantom_creeper_copy = true
				staffof_magic_arrows_2_projectile = true
				skeleton_thrasher_not_despawn = true
				corpse_fly = true

			[light_sources.settings.entities.samurai_dynasty]
				enenra = true
				twotailed = true
				jorogumo = true
				kawauso = true
				komainu = true
				oni = true
				tanuki = true
				kitsune = true
				akaname = true

			[light_sources.settings.entities.traveloptics]
				summoned_wadjet = true
				summoned_ignited_berserker = true
				summoned_koboleton = true
				summoned_draugr = true
				summoned_ignited_revenant = true

			[light_sources.settings.entities.cataclysm]
				lionfish = true
				ignis = true
				koboleton = true
				deepling = true
				ashen_breath = true
				wither_missile = true
				blazing_bone = true
				abyss_orb = true
				earthquake = true
				screen_shake = true
				deepling_angler = true
				amethyst_crab = true
				amethyst_cluster_projectile = true
				ancient_desert_stele = true
				lionfish_spike = true
				deepling_brute = true
				the_prowler = true

			[light_sources.settings.entities.touhou_little_maid]
				power_point = true
				maid = true
				fairy = true

			[light_sources.settings.entities.quark]
				torch_arrow = true
				wraith = true
				totem = true
				forgotten = true
				toretoise = true
				glass_frame = true
				stoneling = true
				foxhound = true
				crab = true

			[light_sources.settings.entities.ars_elemental]
				siren_entity = true

			[light_sources.settings.entities.irons_spellbooks]
				dragon_breath = true
				guiding_bolt = true
				magic_missile = true
				necromancer = true
				archevoker = true
				priest = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				jumping_spider = true
				leaf_insect = true
				koi_fish = true
				dumbo_octopus = true
				ferret = true
				otter = true
				sea_bunny = true

			[light_sources.settings.entities.scguns]
				fire_round_projectile = true
				cog_knight = true
				hive = true
				krahg_round_projectile = true
				sculk_cell = true
				rocket = true
				microjet = true
				cog_minion = true
				advanced_round_projectile = true
				supply_scamp = true
				throwable_grenade = true
				sky_carrier = true
				dissident = true
				beowulf_projectile = true
				ramrod_projectile = true
				redcoat = true

			[light_sources.settings.entities.pointblank]
				smaw_rocket = true

			[light_sources.settings.entities.rootoffear]
				wilted = true
				wilted_barrier = true
				light_extinguisher = true

			[light_sources.settings.entities.endlessbiomes]
				anklor = true
				resistive_sentinel = true
				riftite_sentinel = true
				radon_sentinel = true

			[light_sources.settings.entities.yuushya]
				ride_entity = true

			[light_sources.settings.entities.spartanweaponry]
				throwing_weapon = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				desert_creeper = true
				dark_oak_creeper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.etcetera]
				eggple = true
				chapple = true

			[light_sources.settings.entities.cold_sweat]
				chameleon = true

			[light_sources.settings.entities.aquaculture]
				bluegill = true
				muskellunge = true
				water_arrow = true
				smallmouth_bass = true
				catfish = true

			[light_sources.settings.entities.celestisynth]
				poltergeist_ward = true
				rainfall_turret = true
				solaris_bomb = true
				frostbound_shard = true
				star_monolith = true
				keres_smash = true
				rainfall_rain = true
				keres_shadow = true
				cs_effect = true
				keres_slash = true
				keres_rend = true
				aquaflora_camera = true
				keres_slash_wave = true
				breezebreaker_tornado = true
				rainfall_arrow = true

			[light_sources.settings.entities.trials]
				bogged = true

			[light_sources.settings.entities.crabbersdelight]
				crab = true

			[light_sources.settings.entities.aquamirae]
				maw = true
				anglerfish = true
				golden_moth = true
				spinefish = true

